"""Rename image columns to media

Revision ID: 330b23c7dfc4
Revises: 3efdc94aeaad
Create Date: 2025-11-14 22:35:58.442176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '330b23c7dfc4'
down_revision = '3efdc94aeaad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_url', sa.String(length=512), nullable=True))
        
        # === ОСЬ ФІКС ===
        # Ми додаємо server_default='text'.
        # Це каже базі даних: "Для всіх старих рядків постав 'text'"
        batch_op.add_column(sa.Column('media_type', sa.String(length=50), nullable=False, server_default='text'))
        
        batch_op.drop_column('image_url')
        batch_op.drop_column('is_image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_image', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=512), nullable=True))
        batch_op.drop_column('media_type')
        batch_op.drop_column('media_url')

    # ### end Alembic commands ###