"""Add is_read column to Message

Revision ID: 3ad83a512c55
Revises: 
Create Date: 2025-11-14 19:51:26.842925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ad83a512c55'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('is_image', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('is_read')
        batch_op.drop_column('is_image')
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
